### ISSUE TITLE
how to change the font size of the notifications

### ISSUE THREAD

**Issue by noumanbhatti** [flauc/angular2-notifications#255]
I tired to set the options but couldn't figure it out. Is there a way to set the font-size or the notification box size?

**Comment by flauc** [comment]
Angular isn't very clear on how styles should be handled in third-party libraries.  At the moment this would be your best options: 

```css
:host ::ng-deep simple-notifications .sn-content {
    font-size: 50px;
}

:host ::ng-deep simple-notifications .sn-title {
    font-size: 50px;
}
```
