### ISSUE TITLE
Override default style

### ISSUE THREAD

**Issue by jbouzekri** [flauc/angular2-notifications#33]
Hi @flauc,

Is there a way to override the default style ?

For example, I want to change the z-index of the simple-notification-wrapper div because it displays behind the black opacity overlay of bootstrap modal.

Thanks

**Comment by flauc** [comment]
There wasn't till now. I've added `viewEncapsulation.none` to the component. So if you pull the latest version you can just do this: 

```css
        .simple-notification-wrapper {
            z-index: 10 !important;
        }
```
