### ISSUE TITLE
Notification is not floating on screen

### ISSUE THREAD

**Issue by theunreal** [flauc/angular2-notifications#44]
If my browser is not scrolled to the bottom of the web page, I can't see the notifications. 

The noficiation is not working as "fixed" in my app, although it works fine in the provided demoe.

What can cause it to happen?

**Comment by flauc** [comment]
Hi @theunreal 

There must be some conflict with the css. I've added `encapsulation: ViewEncapsulation.None` because of an user request. So if you have a class with the same name it applies to the notification as well.

**Comment by theunreal** [comment]
@flauc I didn't get from your answer what could have gone wrong and how encapsulation has to do with it?

**Comment by flauc** [comment]
You might have the same class i use defined in some other css file.

**Comment by flauc** [comment]
Inspect the simple notification wrapper and check if the following are the only styles attached to the element:

```css
        .simple-notification-wrapper {
            position: fixed;
            bottom: 20px;
            right: 20px;
            width: 300px;
            z-index: 1000;
        }
```
