### ISSUE TITLE
Configure notification position

### ISSUE THREAD

**Issue by lanocturne** [flauc/angular2-notifications#7]
👏🏾 Great component!

Just wander is there a way to set notification's popup position, let's say set them to top right?

**Comment by flauc** [comment]
Thanks:+1: 

I didn't include an option for that because i thought it was unnecessary. It's easily done with css. I've done it [here](http://flauc.github.io/angular2-notifications) by adding this to my css: 

```css
.simple-notification-wrapper {
    left: 20px;
}
```

By styling the wrapper you can determine the position and shape of the notifications. For example adding this line, positions them on the top of the page: 

```css
.simple-notification-wrapper {
    top: 20px;
}
```
